"""Which tools can change something. Generated by backend/scripts/gen_langbot_tools.py.

Do not edit: run the generator. Derived from the agent registry's scopes so
the side-effect gate cannot fall behind a tool that grew write actions.
"""
from __future__ import annotations

WRITE_CAPABLE: frozenset[str] = frozenset(
    {
        "audit",
        "blog",
        "connect",
        "form_pr",
        "group_pin",
        "inbox",
        "links",
        "product_invite",
        "product_members",
        "scout",
        "scout_approve",
        "scrape",
        "variants",
    }
)

READ_ONLY: frozenset[str] = frozenset(
    {
        "approvals",
        "campaigns",
        "issues",
        "products",
        "report",
        "scout_queue",
        "stats",
    }
)
